import { Alert, Autocomplete, Avatar, Backdrop, Box, Button, Checkbox, CircularProgress, Container, CssBaseline, Dialog, Divider, FormControlLabel, FormHelperText, InputAdornment, InputLabel, LinearProgress, Menu, MenuItem, MenuList, Pagination, Select, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography, Zoom } from '@mui/material'

export const component = {
    Alert,
    Autocomplete,
    Avatar,
    Backdrop,
    Box,
    Button,
    Checkbox,
    CircularProgress,
    Container,
    CssBaseline,
    Dialog,
    Divider,
    FormControlLabel,
    FormHelperText,
    InputAdornment,
    InputLabel,
    LinearProgress,
    Menu,
    MenuItem,
    MenuList,
    Pagination,
    Select,
    Zoom,
    Table,
    TableBody,
    TableCell,
    TableContainer,
    TableHead,
    TableRow,
    TextField,
    Typography,
}
