"""006

Revision ID: 91ece12262b6
Revises: 7037d3164522
Create Date: 2024-05-30 15:59:34.429769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91ece12262b6'
down_revision: Union[str, None] = '7037d3164522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('user_sale_id', sa.UUID(), nullable=True))
    op.add_column('deal', sa.Column('user_project_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_deal_user_project_id'), 'deal', ['user_project_id'], unique=False)
    op.create_index(op.f('ix_deal_user_sale_id'), 'deal', ['user_sale_id'], unique=False)
    op.add_column('lead', sa.Column('user_sale_id', sa.UUID(), nullable=True))
    op.add_column('lead', sa.Column('user_project_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_lead_user_project_id'), 'lead', ['user_project_id'], unique=False)
    op.create_index(op.f('ix_lead_user_sale_id'), 'lead', ['user_sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_user_sale_id'), table_name='lead')
    op.drop_index(op.f('ix_lead_user_project_id'), table_name='lead')
    op.drop_column('lead', 'user_project_id')
    op.drop_column('lead', 'user_sale_id')
    op.drop_index(op.f('ix_deal_user_sale_id'), table_name='deal')
    op.drop_index(op.f('ix_deal_user_project_id'), table_name='deal')
    op.drop_column('deal', 'user_project_id')
    op.drop_column('deal', 'user_sale_id')
    # ### end Alembic commands ###
