"""003

Revision ID: 3da8db219566
Revises: ffc2546293b2
Create Date: 2024-05-19 15:54:23.958306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da8db219566'
down_revision: Union[str, None] = 'ffc2546293b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('company', 'phone',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('company', 'logo',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('deal', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('deal', 'phone',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('lead', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('lead', 'phone',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('user', 'picture',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'picture',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('lead', 'phone',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('lead', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('deal', 'phone',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('deal', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('company', 'logo',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('company', 'phone',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('company', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
