"""004

Revision ID: 0524052ddbba
Revises: 3da8db219566
Create Date: 2024-05-19 17:49:53.627637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0524052ddbba'
down_revision: Union[str, None] = '3da8db219566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('company', 'phone',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('deal', 'name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('deal', 'phone',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('lead', 'name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('lead', 'phone',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('lead', 'phone',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('lead', 'name',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('deal', 'phone',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('deal', 'name',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('company', 'phone',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('company', 'name',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###
