"""002

Revision ID: ffc2546293b2
Revises: 83bb760c4cad
Create Date: 2024-05-19 15:14:28.013465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc2546293b2'
down_revision: Union[str, None] = '83bb760c4cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('email', sa.String(length=128), nullable=True))
    op.add_column('company', sa.Column('phone', sa.String(length=128), nullable=True))
    op.add_column('company', sa.Column('logo', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_company_email'), 'company', ['email'], unique=False)
    op.create_index(op.f('ix_company_phone'), 'company', ['phone'], unique=False)
    op.add_column('deal', sa.Column('email', sa.String(length=128), nullable=True))
    op.add_column('deal', sa.Column('phone', sa.String(length=128), nullable=True))
    op.add_column('deal', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_deal_company_id'), 'deal', ['company_id'], unique=False)
    op.create_index(op.f('ix_deal_email'), 'deal', ['email'], unique=False)
    op.create_index(op.f('ix_deal_phone'), 'deal', ['phone'], unique=False)
    op.add_column('lead', sa.Column('email', sa.String(length=128), nullable=True))
    op.add_column('lead', sa.Column('phone', sa.String(length=128), nullable=True))
    op.add_column('lead', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_lead_company_id'), 'lead', ['company_id'], unique=False)
    op.create_index(op.f('ix_lead_email'), 'lead', ['email'], unique=False)
    op.create_index(op.f('ix_lead_phone'), 'lead', ['phone'], unique=False)
    op.add_column('user', sa.Column('phone', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('picture', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_column('user', 'picture')
    op.drop_column('user', 'phone')
    op.drop_index(op.f('ix_lead_phone'), table_name='lead')
    op.drop_index(op.f('ix_lead_email'), table_name='lead')
    op.drop_index(op.f('ix_lead_company_id'), table_name='lead')
    op.drop_column('lead', 'company_id')
    op.drop_column('lead', 'phone')
    op.drop_column('lead', 'email')
    op.drop_index(op.f('ix_deal_phone'), table_name='deal')
    op.drop_index(op.f('ix_deal_email'), table_name='deal')
    op.drop_index(op.f('ix_deal_company_id'), table_name='deal')
    op.drop_column('deal', 'company_id')
    op.drop_column('deal', 'phone')
    op.drop_column('deal', 'email')
    op.drop_index(op.f('ix_company_phone'), table_name='company')
    op.drop_index(op.f('ix_company_email'), table_name='company')
    op.drop_column('company', 'logo')
    op.drop_column('company', 'phone')
    op.drop_column('company', 'email')
    # ### end Alembic commands ###
