"""001

Revision ID: 83bb760c4cad
Revises: 
Create Date: 2024-05-12 18:19:40.898820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83bb760c4cad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('text', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_created_at'), 'comment', ['created_at'], unique=False)
    op.create_index(op.f('ix_comment_text'), 'comment', ['text'], unique=False)
    op.create_index(op.f('ix_comment_updated_at'), 'comment', ['updated_at'], unique=False)
    op.create_table('company',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_created_at'), 'company', ['created_at'], unique=False)
    op.create_index(op.f('ix_company_is_active'), 'company', ['is_active'], unique=False)
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=False)
    op.create_index(op.f('ix_company_updated_at'), 'company', ['updated_at'], unique=False)
    op.create_table('deal',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_created_at'), 'deal', ['created_at'], unique=False)
    op.create_index(op.f('ix_deal_name'), 'deal', ['name'], unique=False)
    op.create_index(op.f('ix_deal_updated_at'), 'deal', ['updated_at'], unique=False)
    op.create_table('lead',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_created_at'), 'lead', ['created_at'], unique=False)
    op.create_index(op.f('ix_lead_name'), 'lead', ['name'], unique=False)
    op.create_index(op.f('ix_lead_updated_at'), 'lead', ['updated_at'], unique=False)
    op.create_table('user',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('has_permission_of_root', sa.Boolean(), nullable=False),
    sa.Column('has_permission_of_admin', sa.Boolean(), nullable=False),
    sa.Column('has_permission_of_sale', sa.Boolean(), nullable=False),
    sa.Column('has_permission_of_project', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_company_id'), 'user', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_has_permission_of_admin'), 'user', ['has_permission_of_admin'], unique=False)
    op.create_index(op.f('ix_user_has_permission_of_project'), 'user', ['has_permission_of_project'], unique=False)
    op.create_index(op.f('ix_user_has_permission_of_root'), 'user', ['has_permission_of_root'], unique=False)
    op.create_index(op.f('ix_user_has_permission_of_sale'), 'user', ['has_permission_of_sale'], unique=False)
    op.create_index(op.f('ix_user_is_active'), 'user', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_updated_at'), 'user', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_updated_at'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_is_active'), table_name='user')
    op.drop_index(op.f('ix_user_has_permission_of_sale'), table_name='user')
    op.drop_index(op.f('ix_user_has_permission_of_root'), table_name='user')
    op.drop_index(op.f('ix_user_has_permission_of_project'), table_name='user')
    op.drop_index(op.f('ix_user_has_permission_of_admin'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_index(op.f('ix_user_company_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_lead_updated_at'), table_name='lead')
    op.drop_index(op.f('ix_lead_name'), table_name='lead')
    op.drop_index(op.f('ix_lead_created_at'), table_name='lead')
    op.drop_table('lead')
    op.drop_index(op.f('ix_deal_updated_at'), table_name='deal')
    op.drop_index(op.f('ix_deal_name'), table_name='deal')
    op.drop_index(op.f('ix_deal_created_at'), table_name='deal')
    op.drop_table('deal')
    op.drop_index(op.f('ix_company_updated_at'), table_name='company')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_index(op.f('ix_company_is_active'), table_name='company')
    op.drop_index(op.f('ix_company_created_at'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_comment_updated_at'), table_name='comment')
    op.drop_index(op.f('ix_comment_text'), table_name='comment')
    op.drop_index(op.f('ix_comment_created_at'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
